server:
  port: 8080

spring:
  application:
    name: reservation-system

  datasource:
    url: jdbc:mysql://localhost:3306/azki_reservation?useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000
      pool-name: ReservationHikariPool

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: always
      continue-on-error: false

logging:
  level:
    com.azki.reservation: INFO
    org.hibernate.SQL: WARN